[font]
size = 12.0

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[general]
import = [
    "~/.config/alacritty/themes/themes/baitong.toml"
]

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }
blink_interval = 500
blink_timeout = 0
unfocused_hollow = true
thickness = 0.15
